[[constraint]]
  name = "github.com/monzo/terrors"
  branch = "master"

[[constraint]]
  name = "github.com/monzo/typhon"
  branch = "master"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "kubernetes-1.15.0"