apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: wylis
  name: wylis
  namespace: default
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wylis
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9051'
      creationTimestamp: null
      labels:
        app: wylis
    spec:
      containers:
      - env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: icydoge/web:wylis-15b6166
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9050
          protocol: TCP
        - containerPort: 9051
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9050
          initialDelaySeconds: 5
          periodSeconds: 5
        name: wylis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: wylis
      serviceAccountName: wylis
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        operator: Exists
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wylis
  namespace: default

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: wylis
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: wylis
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wylis
subjects:
- kind: ServiceAccount
  name: wylis
  namespace: default

